version: '3.7'
services:
  code_editor_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: code_editor_app:latest
    ports:
      - "3001:3001"
    networks:
      - editor_network
    volumes:
      - .:/usr/src/app
networks:
  editor_network:
    driver: bridge
    name: editor_network
